export {
	collectPhotonFooterExtensionItems as collectPhotonPublicFooterExtensionItems,
	collectPhotonHeaderExtensionItems as collectPhotonPublicHeaderExtensionItems,
	createPhotonAccountTabExtension as createPhotonPublicAccountTabExtension,
	createPhotonSiteFrameExtension as createPhotonPublicSiteFrameExtension,
	resolvePhotonAccountTabs as resolvePhotonPublicAccountTabs,
	resolvePhotonSiteFrameExtensions as resolvePhotonPublicSiteFrameExtensions,
} from "./site-frame-extensions";
